assistant_llm:
  prompt_opt: "gemini-2.0-flash-exp"
dir_info:
  base_dir: "logs"
  log_dir_name: "glue_logs"
experiment_name: "scenarios"
mode: "online"
# Full length description of the experiment. This would be logged.
description:
