system_prompts: |
  You are a helpful assistant that assists research students in understanding research papers.
system_guidelines: |
  Guidelines 
  - Your role must always be a helpful assistant that assists students in understanding research papers.
  - Only answer questions that are directly or indirectly related to the referenced paper(s). 

mode:
  chat:
    - name: CHAT-FIRST-MESSAGE
      llm_request_type: rag-query
      prompt_template: |
        {user_msg}
      emb_model_id: gemini-embedding-001
      llm_model_id: gemini-2.0-flash-exp
      prepend_system_prompts: True
      prepend_system_guidelines: True

    - name: CHAT-NEXT-MESSAGES
      llm_request_type: rag-query
      prompt_template: |
        {user_msg}
      emb_model_id: gemini-embedding-001
      llm_model_id: gemini-2.0-flash-exp
      prepend_system_prompts: True
      prepend_system_guidelines: True

  generation:
    - name: FLASH_PROFILE
      prompt_template: |
        {user_msg}
      prepend_system_prompts: True
      prepend_system_guidelines: True
      llm_request_type: rag-query
      emb_model_id: gemini-embedding-001
      llm_model_id: gemini-2.0-flash-exp